daysUntilStale: 14
daysUntilClose: 3
exemptLabels:
  - "state: completed"
  - "state: confirmed"
  - "state: help wanted/needed"
  - "state: in progress"
staleLabel: "type: abandoned"
markComment: >
  This submission has been automatically marked as abandoned because it has not had recent activity. It will be closed in 3 days. If you want to prevent that, leave a new comment.
closeComment: >
  Due to no recent activity, this submission is closed now.
