group = com.almostreliable
license = MIT

# Mod options
modId = ponderjs
modName = PonderJS
modVersion = 2.1.1
modAuthor = AlmostReliable
modDescription = Allows creating ponder scenes and tags with KubeJS.
modAuthors= kotakotik22, AlmostReliable
modCredits= Continuation of kotakotik22 mod.

# Common
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.93
kubejsVersion = 2101.7.1-build.181

# Deps
ponderVersion = 1.0.46
flywheelVersion = 1.0.4-27

# AlmostGradle
almostgradle.launchArgs.resizeClient = true
almostgradle.launchArgs.autoWorldJoin = true

almostgradle.recipeViewers.emi.version = 1.1.12
almostgradle.recipeViewers.emi.minecraftVersion = 1.21

# Parchment
neoForge.parchment.minecraftVersion = 1.21
neoForge.parchment.mappingsVersion = 2024.07.07

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
