modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "https://github.com/${github_user}/${github_repo}/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
Allows creating ponder scenes and tags with Kubejs
'''

[[dependencies.ponderjs]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "create"
mandatory = true
versionRange = "[${create_min_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_min_version},)"
ordering = "AFTER"
side = "BOTH"
