modLoader = "javafml"
loaderVersion = "[${forge_min_version},)"
issueTrackerURL = "https://github.com/${github_user}/${github_repo}/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.ponderjs]]
modId = "forge"
mandatory = true
versionRange = "[${forge_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "create"
mandatory = true
versionRange = "[${create_min_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_min_version},)"
ordering = "AFTER"
side = "BOTH"
