modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
credits = "${modCredits}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.ponderjs]]
modId = "forge"
mandatory = true
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ponderjs]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_min_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ponderjs.mixins.json"
